# Generated by Django 5.0.1 on 2024-05-03 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="published_cate",
            new_name="published_date",
        ),
    ]
